common:
  org: trilix
  loglevel: info
  amqplogging: false
  consolelogging: true
  settingsfiles:
    - settings.yaml
  app:
    port: 3000
    rpc_timeout: 35s

rabbitmq:
  primary:
    default: true
    host: localhost
    vhost: trilix
    port: 5672
    username: trilix
    password: secret

